use-ink/contracts-ui

src/api/contract/call.ts
src/api/instantiate/createInstantiateTx.ts
src/api/util/index.tsx
src/constants/index.ts
src/types/substrate.ts
src/types/ui/contract.ts
src/ui/components/contract/Interact.tsx
src/ui/components/form/Input.tsx
src/ui/components/form/InputGas.tsx
src/ui/components/form/InputNumber.tsx
src/ui/components/instantiate/Step2.tsx
src/ui/contexts/InstantiateContext.tsx
src/ui/hooks/useMetadata.ts

- InputGas component to handle weight/megagas selection
- Use dryrun (RPC) to prefill and use estimated weight for calls by default
- Add option to use estimated or custom gas limit

Estimated gas & gas input component

---

src/api/instantiate/instantiate.ts
src/api/util/index.tsx
src/types/ui/contexts.ts
src/ui/components/Transactions.tsx
src/ui/components/homepage/Statistics.tsx
src/ui/components/instantiate/Step3.tsx
src/ui/contexts/TransactionsContext.tsx
src/ui/hooks/useQueueTx.ts

display notifications for events emitted during instantiation 
handle tx errors differently 
clear homepage subscription
tx status refactoring so that it can have one value at a time
closes https://github.com/paritytech/substrate-contracts-explorer/issues/128
closes https://github.com/paritytech/substrate-contracts-explorer/issues/84

Display event notifications

---

src/ui/components/common/Dropdown.tsx
src/ui/components/instantiate/Step2.tsx
src/ui/contexts/ApiContext.tsx
src/ui/hooks/useArgValues.ts

No accounts found bug fixed

---

src/api/chainProps.ts
src/api/connect.ts
src/api/index.ts
src/api/loadAccounts.ts
src/api/util/index.ts
src/constants/index.ts
src/types/substrate.ts
src/types/ui/contexts.ts
src/ui/components/account/AccountSelect.tsx
src/ui/components/contract/Interact.tsx
src/ui/components/instantiate/Step2.tsx
src/ui/components/sidebar/NetworkAndUser.tsx
src/ui/contexts/ApiContext.tsx
src/ui/reducers/api.ts
src/ui/util/dropdown.tsx
src/ui/util/index.ts

closes https://github.com/paritytech/substrate-contracts-explorer/issues/5

Implement node switch, fix dep cycle

---

src/ui/contexts/TransactionsContext.tsx

Closes #181 
Handle injected accounts correctly when sending txs

Allow external account signing

---

package.json
src/db/queries/codeBundle.ts
src/db/queries/contract.ts
src/ui/components/contract/ContractRow.tsx
src/ui/hooks/useAvailableCodeBundles.ts
src/ui/pages/Contract.tsx
src/ui/util/index.ts
yarn.lock

Remove moment.js

---

src/ui/components/account/Select.tsx
src/ui/components/account/index.ts
src/ui/components/form/findComponent.tsx
src/ui/components/form/hooks/useAccountField.tsx
src/ui/hooks/useAccountId.ts

Closes #203 
Use only keyring accounts for transaction-related dropdowns and all addresses for interacting

Distinguish between accounts and addresses

---

package.json
yarn.lock

Fix threaddb issue

---

src/types/substrate.ts
src/types/ui/components.ts
src/ui/components/contract/Interact.tsx
src/ui/components/form/ArgumentForm.tsx
src/ui/components/form/Enum.tsx
src/ui/components/form/findComponent.tsx
src/ui/components/instantiate/Step2.tsx
src/ui/components/message/ArgSignature.tsx
src/ui/util/initValue.ts

Closes #217 
Relevant to #223 - important to pass contract abi registry so correct components and types are found

Support enum and si types

---

src/ui/components/form/Option.tsx
src/ui/components/form/findComponent.tsx
src/ui/util/initValue.ts

Add Option<T> type support

---

vite.config.ts

Reverts paritytech/contracts-ui#276

Revert "Set deployment base and local port"

---

src/ui/components/homepage/HelpBox.tsx

- Show survey card and remove ability for user to permanently close it

Always display survey prompt

---

src/ui/components/instantiate/Step1.tsx

Closes #320 
- Only update contract name input when a different file is uploaded

Prevent contract name bug

---

src/api/loadAccounts.ts
src/types/ui/contexts.ts
src/ui/components/AwaitApis.tsx
src/ui/components/common/AccountsError.tsx
src/ui/components/common/ConnectionError.tsx
src/ui/components/common/Error.tsx
src/ui/reducers/api.ts
src/ui/styles/base.css

Based on https://github.com/paritytech/contracts-ui/pull/321 
Improved the `loadAccounts` flow 
- dispatch keyring error if extension not installed instead of adding one more boolean in global state. 
- removed try catch - nothing to catch there
Improved error messages

Improve extension detection and errors

---

src/ui/components/App.tsx
src/ui/components/sidebar/Footer.tsx
src/ui/components/sidebar/MobileMenu.tsx
src/ui/components/sidebar/QuickLinks.tsx
src/ui/components/sidebar/index.tsx
src/ui/styles/link.css
src/ui/styles/sidebar.css

Hide sidebar on mobile portrait mode and use mobile menu instead.

Mobile menu

---

src/ui/components/form/VectorFixed.tsx

closes https://github.com/paritytech/contracts-ui/issues/338

Fix array bug

---

cypress.config.ts
cypress/support/e2e.ts
package.json
vite.config.ts
yarn.lock

closes https://github.com/paritytech/contracts-ui/issues/259

Collect coverage

---

src/helpers/util/util.ts
src/ui/contexts/TransactionsContext.tsx
src/ui/hooks/useNewContract.ts

Stop waiting for finalization + remove some unused code

Wait for block inclusion

---

src/ui/components/common/CopyButton.tsx
src/ui/components/common/SearchResults.tsx
src/ui/components/contract/DryRunResult.tsx
src/ui/components/contract/OutcomeItem.tsx
src/ui/components/form/hooks/useMetadataField.tsx
src/ui/components/instantiate/LookUpCodeHash.tsx
src/ui/pages/Contract.tsx

fixes https://github.com/paritytech/contracts-ui/issues/378

Fix code hash lookup 

---

src/db/index.ts
src/helpers/util/util.ts
src/ui/components/form/hooks/useMetadataField.tsx
src/ui/index.tsx
src/ui/pages/AddContract.tsx
src/ui/pages/AddressLookup.tsx
src/ui/pages/Contract.tsx
src/ui/pages/index.ts

closes https://github.com/paritytech/contracts-ui/issues/213

Add contract from address

---

src/helpers/util.ts

fixes https://github.com/paritytech/contracts-ui/issues/389

Fix address validation

---

.github/ISSUE_TEMPLATE/bug_report.md

Add more info about the environment to the new issue template

chore: extend new issue template

---

src/ui/components/common/AccountsError.tsx

The faucet links for Astar and AZero changed

chore: update faucet links

---

src/types/ui/components.ts
src/ui/components/account/Select.tsx
src/ui/components/common/Dropdown.tsx

closes https://github.com/paritytech/contracts-ui/issues/403

feat: external address in select

---

src/ui/components/form/OptionsForm.tsx

closes https://github.com/paritytech/contracts-ui/issues/422

chore: change info text for `gasLimit`

---

package.json
src/helpers/output.ts
src/ui/components/contract/OutcomeItem.tsx
yarn.lock

related to https://github.com/paritytech/contracts-ui/issues/421

fix: pretty print dry-run results

---

src/constants/index.ts

Until we figure out https://github.com/paritytech/contracts-ui/issues/446 i removed the Peaq Agung testnet

fix: remove unsupported chain

---

src/constants/index.ts

Added data to connect to Astar main-net

Adding Astar mainnet

---

src/ui/components/homepage/HelpBox.tsx
src/ui/components/metadata/GetPatronMetadata.ts
src/ui/pages/ContractHeader.tsx

Was complaining about order of props and missing header comment.

chore: resolves linter warnings

---

package.json
src/ui/components/App.tsx
src/ui/components/CheckBrowserSupport.tsx
src/ui/components/common/Info.tsx
src/ui/components/common/UnsupportedBrowserMessage.tsx
src/ui/components/index.ts
yarn.lock

Closes #400.
Can be tested by visiting the branch deploy preview with Safari.
=> https://deploy-preview-549--contracts-ui.netlify.app/

feat: shows an unsupported browser message when using Safari
