- __test-utils__/mocks/db.ts
- __tests__/db/queries/index.test.ts
- src/api/instantiate/instantiate.ts
- src/api/util/blockTime.ts
- src/constants/index.ts
- src/db/queries/codeBundle.ts
- src/db/queries/contract.ts
- src/db/queries/index.ts
- src/db/schemas/codeBundle.schema.json
- src/db/schemas/contract.schema.json
- src/db/util/init.ts
- src/types/db.ts
- src/types/ui/contexts.ts
- src/ui/contexts/ApiContext.tsx
- src/ui/contexts/DatabaseContext.tsx
- src/ui/hooks/useBlockTime.ts
- src/ui/hooks/useCodeBundle.ts
- src/ui/hooks/useWeight.ts
- Refactor database name to combine RPC url and block one hash
- On startup, wait for block 1 to pass to ensure correct db name is used
- Clear unused local dbs once the block hash no longer matches
- Removes blockOneHash/blockZeroHash from document schemas - now unnecessary
closes https://github.com/paritytech/substrate-contracts-explorer/issues/126
> IndexedDB name refactoring

- src/api/instantiate/createInstantiateTx.ts
- src/ui/components/instantiate/Step2.tsx
- src/ui/components/instantiate/Step3.tsx
show a value input only when constructor is payable
salt enabled by default
when salt is disabled `ContractTrapped` happens, as expected
disable back button while processing instantiation
> Final adjustments

- package.json
- src/db/schemas/codeBundle.schema.json
- src/db/schemas/contract.schema.json
- yarn.lock
This reverts commit abf6ee63a76e5bdebf43e1068ecb07d0e756b720, reversing
changes made to 6efabd5e3f6e9d369e2397a30e987a88efbb5666.
even though it seemed to work at first, the trhreaddb reversion only brings out older bugs 
app doesn't work and this is printed in the console:
`Error: unknown format "email" ignored in schema at path "#/properties/email"`
> Revert "Merge pull request #208 from paritytech/ki-revert-threaddb"

- src/types/ui/contract.ts
- src/ui/components/contract/Interact.tsx
- src/ui/components/contract/QueryResult.tsx
- src/ui/components/form/InputBalance.tsx
Consistent BN formatting for inputs and results output 
Hide the units dropdown in `InputBalance` as it's not yet functional
For user input `1234` you got back `1,234,000,000,000,000` in the results output panel. This PR fixes that.
> Show better formatted BN in call results

- src/ui/components/contract/QueryResult.tsx
Calling `get()` on an `incrementer` contract always returns `0` no matter what initial value you pass or how much you increment.
The problem was introduced in https://github.com/paritytech/contracts-ui/pull/218 which should apply only to `u128` return types, not all `BN`
> Fix `BN` display for query results

- src/ui/components/form/findComponent.tsx
While trying to find a contract with `Option` inputs, i tried to deploy[ the contract ](https://github.com/agryaznov/candle-auction-ink/releases/tag/v0.2.3) used to open the issue in the first place. It resulted in a white screen when going to step 2 of the instantiation form. 
After some debugging, turns out the app was trying to load a Vector component for the Option input.
This PR fixes that, now the app displays the default case, a plain HTML text input 
related to https://github.com/paritytech/contracts-ui/issues/161
> Correctly assign Vector components to `Vec` input types

- src/api/util/index.ts
- src/types/substrate.ts
- src/types/ui/contract.ts
- src/ui/components/contract/Interact.tsx
- src/ui/components/contract/TransactionResult.tsx
- src/ui/contexts/TransactionsContext.tsx
Makes no sense to keep the UI blocked until the block is finalized on development chains. This way transactions on the local node finish much sooner. Significantly speeds up e2e tests.
closes https://github.com/paritytech/contracts-ui/issues/230
> Display results and events on block inclusion

- src/types/ui/contexts.ts
- src/ui/components/contract/Interact.tsx
- src/ui/components/contract/TransactionResult.tsx
- src/ui/components/instantiate/DryRun.tsx
- src/ui/contexts/TransactionsContext.tsx
Currently when a contract call fails, the app shows a success notification and no error message anywhere. 
This PR prints humanly readable errors in the results panel and displays an error notification as expected. 
Other than that, error docs are now displayed in the instantiate dry run results. Something similar should be done with the next iteration of the Interact page, but this should work for now.
closes https://github.com/paritytech/contracts-ui/issues/239
closes https://github.com/paritytech/contracts-ui/issues/27
> Better error messages in the app

- src/api/chainProps.ts
- src/api/connect.ts
- src/constants/index.ts
- src/db/util/init.ts
- src/types/ui/contexts.ts
- src/ui/contexts/DatabaseContext.tsx
App doesn't connect to the latest version of `contracts-node` because it endlessly waits for block#1 to initialize the db and that doesn't happen automatically anymore
> Fix connection error on `contracts-node` 0.11.0

- package.json
- yarn.lock
Fix dependabot alert about Improper Verification of Cryptographic Signature in `node-forge`
> Patch `node-forge` 

- src/ui/index.tsx
- src/ui/pages/NotFound.tsx
- src/ui/pages/index.ts
closes https://github.com/paritytech/contracts-ui/issues/221
We should consider migrating to `BrowserRouter` when we finally kill GH Pages deployment.
Because of how `HashRouter` works the `NotFound` page isn't loaded when there is no `#` in the url and a default error page is shown.
> Add not found route

- vite.config.ts
The vite config was missing the `base` for the deployment URL
Set local port back to 8081 (as it was with webpack)
> Set deployment base and local port

- .github/workflows/deploy.yml
Simplify deploy workflow and fix [this issue](https://github.com/actions/checkout/issues/760) which was happening with the  `ad-m/github-push-action@v0.5.0` action which was used to push to the `gh-pages` branch
> Change deploy workflow

- package.json
- src/ui/components/account/Identicon.tsx
- src/ui/components/common/Button.tsx
- src/ui/components/common/CopyButton.tsx
- src/ui/components/contract/QueryResult.tsx
- src/ui/components/form/InputGas.tsx
- src/ui/pages/Contract.tsx
- src/ui/styles/main.css
- src/ui/templates/PageFull.tsx
- src/ui/util/index.ts
- yarn.lock
Closes #66 
- Add CopyButton component
- Add copy button to query results and contract address in contract page header
- Copy contract address when identicon is clicked
- Add forwarded ref for Button base component
- Style and z-index adjustments
> Add copy button, add copiable contract address and identicons

- .github/actions/prepare/action.yml
- .github/workflows/build.yml
- .gitignore
- cypress.json
- netlify.toml
- package.json
- src/ui/components/Transactions.tsx
closes https://github.com/paritytech/contracts-ui/issues/260
Now Cypress tests for Firefox and Chrome are run on push via Github Actions. A `contracts-node` binary is downloaded and stored as artifact, then retrieved and executed in the background in the actual test jobs.
Currently each job runs in 2 containers, but can be scaled up to 5 when we have more tests.
The Cypress Netlify Plugin is no longer needed, the status checks fail in pull requests. 
A dependency of ThreadDB is causing the `yarn install` to fail on `Node.js `> 14 and take a long time in general. 
Should be fixed with https://github.com/paritytech/contracts-ui/pull/302
> Run Cypress tests in CI

- src/api/connect.ts
- src/ui/components/Transactions.tsx
Closes #282 
- Overrides DispatchError type to accommodate current substrate-contracts-node metadata
> Override DispatchError type error field

- src/constants/index.ts
- src/ui/components/sidebar/NetworkAndUser.tsx
Shibuya and Shiden networks support pallet-contracts.
It would be great if developers could deploy and interact with contracts on these networks via contracts-ui.
> Add Shibuya and Shiden to network options

- cypress/e2e/extension.spec.ts
- src/constants/index.ts
- src/ui/components/common/AccountsError.tsx
- src/ui/components/sidebar/NetworkAndUser.tsx
`pallet-contracts` was added to the network several months ago and there are more than 1k contracts deployed. Would be great to allow developers to use `contracts-ui`.
> Add Aleph Zero Testnet

- .github/workflows/e2e-tests.yml
Cypress fails with weird "server error" when it runs in parallel and the time save is not worth debugging
> fix: run e2e tests serially

- src/ui/components/common/HeaderButtons.tsx
- src/ui/components/homepage/Contracts.tsx
- src/ui/components/modal/ForgetAllContractsModal.tsx
- src/ui/components/modal/ForgetContractModal.tsx
- src/ui/components/modal/index.ts
Adds new "Forget All Contracts" button, to easily remove all known contracts from the browsers LocalStorage as described in #414. 
It's only available in in the `Contracts` overview to keep the sidebar clean.
> feat: remove all contracts button

- package.json
- src/ui/components/account/Identicon.tsx
- src/ui/components/common/CopyButton.tsx
- src/ui/components/form/FormField.tsx
- src/ui/components/instantiate/CodeHash.tsx
- src/ui/index.tsx
- yarn.lock
The hash of the deployed contract can now easily be copied from the contract page  itself.
I've took the liberty to upgrade the used `react-tooltip` library from v4 to v5, which fixes a displaying issue present with v4.
> feat: allow users to copy the code hash

- src/constants/index.ts
- src/ui/components/common/ConnectionError.tsx
- src/ui/components/sidebar/NetworkAndUser.tsx
- src/ui/contexts/ApiContext.tsx
adds all `awesome ink` listed chains:
https://github.com/paritytech/awesome-ink#-networks-where-you-can-deploy-ink-contracts
Yes it's a bit messy, it seems there is no single good resource to get all information about parachains to use in a software project yet. It's cumbersome to maintain it this way and quite a hassle collection this information from the individual docs.
> feat: add more testnets to dropdown

- src/ui/templates/Page.tsx
Described initially in #290.
Enables scrolling if content overflows vertically. Removes some h-full as it's making the content overflow with white space showing the scrollbar unnecessarily.
> fix: allow scroll if page content overflows vertically.

- src/constants/index.ts
Adds Aleph Zero to list of choosable mainnets with contracts pallets.
Also sorts test and mainnets alphabetically.
> feat: adds Aleph Zero mainnet

- src/helpers/initValue.ts
- src/ui/components/form/findComponent.tsx
The `Vec<u8>` type is often used to represent strings so the changes in https://github.com/paritytech/contracts-ui/pull/451 make the UI unusable in many cases.
Will need to adapt the input to accept strings.
> fix: display text inputs for `Bytes`

- src/ui/components/message/MessageSignature.tsx
this PR solved issue #487 
I think these colors work well in a light theme.
> fix: add colors for the light theme

- src/ui/components/contract/Interact.tsx
This PR solved the issue #445 and execute a dry-run after a contract call
> fix: execute dry run after a call

- src/ui/components/form/InputBytes.tsx
- src/ui/components/form/findComponent.tsx
makes use of `<InputBytes/>` for `VecFixed` with Sub u8, which is usually easier to input encoded has hex. Closes #416.
Using the plain `Input` component to recreate some behavior of the InputHex one. However doing the checking hex step in the `validation` function. Therefore allowing not hex characters, but allows for empty value and less hassle of pasting a copied hex string to this input field.
Tested with `String`, `Hash` and `Vec<u8>` types if there is some overlap regarding input rendering. These inputs are not touched by this PR.
https://github.com/paritytech/contracts-ui/assets/839848/4e715f5e-0411-411c-90d6-fd4cbfbfca24
Contract `input-types`:
https://filebin.net/41e8q8cyl9yvf1g9
> feat: use `<InputBytes/>` for `[u8, n]` type

- src/ui/components/contract/TransactionResult.tsx
fixes error reported in #447 
using the array index in the key string should work fine long the events list is not rearranged. 
if that were the case, then using random ids would be better, its suboptimal for performance as it causes renders but we wont have unexpected behavior.
> fix: duplicated keys

- src/constants/index.ts
Zeitgeist has added smart contracts to their TestNet chain, and this PR adds their Battery Station.
> feat: add testnet `Zeitgeist Battery Station`

- src/ui/components/homepage/HelpBox.tsx
> feat: links to `use.ink` and `ink-examples`

- src/lib/callOptions.ts
Resolves #517.
This function turned every js falsy value, like `false`, `""`, `0` into `null`, thereby preventing passing these actual values as inputs to contract calls.
https://github.com/paritytech/contracts-ui/blob/2387223e1c9d5b0430831141862afea0e834382b/src/lib/callOptions.ts#L56-L70
> fix: prevents turning falsy values into `null`

- src/ui/components/form/InputFile.tsx
- src/ui/components/metadata/GetPatronMetadata.ts
Hi Parity Technologies team!
As we said before, [Brushfam](https://brushfam.io/) team wants to add a URL parameter to automatically set `bundle.contract` file to the`/instantiate` route on your App. So that we can integrate our [Patron](https://github.com/Brushfam/patron-backend) product with countracts-ui and fetch our metadata.
I've added file-creating logic to `InputFile.tsx` and that will affect only the case when a link contains Patron parameter, so it won't change anything for the default flow of your App. Also, I added `eslint-disable-next-line` on the 77 line, because `metadataResponse` is always a JSON type, and for this type, we can add a new field using dot syntax.
Thank you for your communication and for any feedback =)
> feat: Patron integration

- src/ui/components/contract/DryRunResult.tsx
- src/ui/components/instantiate/Step3.tsx
- src/ui/components/instantiate/Wizard.tsx
- src/ui/pages/Instantiate.tsx
Before we did not use the `RootLayout` on the `/instatiate` route, which caused the page to jump on navigation.
https://github.com/paritytech/contracts-ui/assets/839848/44aec7ce-1f78-4e94-bef5-a01d80383e30
Before we used a lot of space and showed truncated values for code hash and extrinsic data. This truncated data was lossy, the user was not able to copy the whole value through the truncation. 
Now it shows both values in full and each value on a dedicated row. Making it as transparent as possible what is going to happen.
Uses newer css `gap` feature instead of multiple usages of `mb`/`margin-bottom` on individual elements.
> chore: ui polish 💅 

- .github/workflows/unit-tests.yml
- package.json
- src/lib/formatBalance.test.ts
- src/lib/formatBalance.ts
- src/ui/components/common/ObservedBalance.tsx
- src/ui/components/contract/ContractRow.tsx
- src/ui/pages/ContractHeader.tsx
- yarn.lock
Resolves #521.
https://github.com/paritytech/contracts-ui/assets/839848/f4e5c914-d201-47e8-b446-f7cde6bd9620
> feat: shows `free` balance of contracts

- src/ui/contexts/TransactionsContext.tsx
Resolves #513/#520 by referring to the selected account if it's a testing account or not and acting accordingly.
This is the actual change:
https://github.com/paritytech/contracts-ui/pull/527/files#diff-d22473d5f78c6d4516163586c619fa5d61e960611e085cd39c676ab0afe72e81R41-R53
The rest just got reformatted due to a now shorter line: 
https://github.com/paritytech/contracts-ui/pull/527/files#diff-d22473d5f78c6d4516163586c619fa5d61e960611e085cd39c676ab0afe72e81R56-R93
> fix: #513 sign with injected wallets on local node

- .github/workflows/build.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/unit-tests.yml
- .github/workflows/validate-pr-title.yml
Before we run some workflows for every branch even if no PR was created. As the checks are not yet relevant, we can save on the CI minutes by running them only on PRs and `master` pushes.
> chore: only runs CI on pull requests & `master`

- src/constants/index.ts
The PoC5 testnet is deprecated and took down soon, so this PR propose for update the endpoint URL to the testnet.
> chore: Update Phala testnet endpoint URL

- .github/actions/prepare/action.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/unit-tests.yml
The following used GitHub actions used node 16, a no longer maintained version. No applicable breaking changes where introduced in the next versions.
+ actions/download-artifact@v3
+ actions/upload-artifact@v3
+ actions/checkout@3
+ cypress-io/github-action@v5.0.5
> chore: upgrades GitHub Actions which where using outdated node versions

- src/lib/callOptions.ts
- src/ui/components/instantiate/Step2.tsx
Closes #382.
The ui was encoding the salt during dryrunning the instantiate of contracts but not during the actual instantiation. Therefore the contract address shown from the dry run result was not matching the actual deployed contract address.
Video showing the bug before and after fix:
https://github.com/paritytech/contracts-ui/assets/839848/5a5b9b7b-a0b6-4697-883f-dd46037ad913
Can be tested on the deploy preview.
> fix: removes unecessary encoding of salt during dryrun

- src/ui/components/contract/Interact.tsx
- src/ui/components/instantiate/Step1.tsx
- src/ui/hooks/useAccountAvailable.ts
Closes #458 .
As our `AccountSelect` allows for creating new select options on the fly, the user can create new options which are not available to sign a deployment or a contract call extrinsic. I added a second layer validation of this value in the deploy and interaction of contracts. 
Disabling the creation of options on the fly is not what we want, as this component is used as a general account input. In this case we want to offer the user to select known accounts but also put it any valid account id.
The demo shows the error first on the latest deployed version of `contracts-ui` and later the behavior with the changes in this branch.
https://github.com/paritytech/contracts-ui/assets/839848/61d1c3be-8094-4996-b0bb-767f1bd968eb
> fix: requires selected account for interaction to be available

- FAUCETS.md
- snapshots.js
- src/constants/index.ts
- src/ui/components/contract/DryRunResult.tsx
- src/ui/styles/dropdown.css
Adds Pop Network Testnet to the list of Testnets available in the drop down.
Adds a link to Paseo's faucet and Pop Network token onboarding page to FAUCETS.md 
Changes introduced to `snapshots.js` and `src/ui/components/contract/DryRunResult.tsx` after linting the code.
> feat: Add Pop Network Testnet

- CODE_OF_CONDUCT.md
- src/ui/layout/sidebar/Footer.tsx
As we want to apply for the open source plan of netlify for deploying this repository, I've added a `Code of Conduct` from the `ink` repository and added a link in the footer to the netlify page. These changes are required to apply for the open source plan.
https://www.netlify.com/legal/open-source-policy/
> chore: meet netlify open source plan requirements
